#!/usr/bin/env ruby
require 'yaml'

# user-configurables
mysql = 'mysql'

# command line-readables
site = 'nedocs-online'
hospital = ARGV.shift || ENV['RAILS_HOSPITAL']
env = ARGV.shift || ENV['RAILS_ENV'] || 'development'

# leave-aloneables
RAILS_ROOT = File.join(File.dirname(__FILE__), '..', '..', '..')
SITE_ROOT = File.join(RAILS_ROOT, 'sites', site)
print "SITE ROOT: #{SITE_ROOT}\n\n"

yml = YAML.load_file(File.join(SITE_ROOT, 'config', 'database.yml'))

print "Hospital: #{hospital}\n\n"

db = case hospital
  when 'master' then yml['master_' + env]['database']
  when 'sessions' then yml[env]['database']
  when 'test' then yml['test']['database']
  else yml[env]['database'] + '_' + hospital
end

print "Database: #{db}\n\n"

mysql += " -u #{yml[env]['username']}"
mysql += " -p'#{yml[env]['password']}'" if yml[env]['password']

# drop database if this is just dev
if env == 'development'
  print `#{mysql} -e 'drop database #{db}'`
end
print `#{mysql} -e 'create database #{db}'`

# if we want to make the test database
if hospital == "test"
  RAILS_HOSPITAL="test"
  print `rake _0.7.3_db:test:prepare`
else
  # run migrations
  print `rake _0.7.3_db:migrate RAILS_HOSPITAL=#{hospital}`
end

# for dev, create sample data
if env == 'development' && hospital != 'sessions'
  print `RAILS_HOSPITAL=#{hospital} ruby #{SITE_ROOT}/script/console #{env} < #{SITE_ROOT}/db/create_sample_data_#{hospital}.rb`
end
